# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "test"
  lane :test do
    run_tests(
      project: "ComparePrices.xcodeproj",
      output_directory: "fastlane/output",
      output_types: "html",
      devices: ["iPhone 12"],
      scheme: "ComparePrices_Develop"
    )
  end

  desc "lint"
  lane :lint do
    swiftlint(
      mode: :lint,      
      reporter: "html",
      executable: "swiftlint", 
      output_file: "fastlane/output/swiftlint.result.html", 
      config_file: ".swiftlint.yml",
      strict: true
    )
  end
end
